# Generated by Django 3.1.7 on 2021-03-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title', max_length=38)),
                ('stars', models.CharField(choices=[('1', '*'), ('2', '* *'), ('3', '* * *'), ('4', '* * * *'), ('5', '* * * * *')], max_length=35)),
                ('description', models.TextField(blank=True, max_length=256)),
                ('price', models.IntegerField(default=0)),
                ('published', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
